version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      timezone: Asia/Tokyo
    versioning-strategy: increase
    groups:
      testcontainers:
        applies-to: version-updates
        patterns:
          - "testcontainers"
          - "@testcontainers/*"

